export {
	CLI_FOLDER,
	CONF_EXTRACTS,
	CONF_GENERATORS,
	CONF_INITS,
	CONF_STARTERS,
	CONFIG_FILE,
	CONFIG_FILE_EXT,
	CONFIG_FILE_TYPE,
	DESCRIPTION,
	DIRNAMES_FILE,
	EXTRACT_PLOP_FILE,
	GEN_FILE_EXT,
	GEN_FILE_TYPE,
	INIT_PLOP_FILE,
	NAME,
	PLOP_FILE,
	ROOT_KEY,
	VERSION,
} from "./config";
export { DIRS } from "./dirs";
export { GEN_OBJECT } from "./genObject";
export { DEFAULT_INIT } from "./init";
export {
	REG_CMD_OPTION_VALUE,
	REG_CMD_SKIP_PARAMS_KEY,
	REG_IS_DIRS,
	REG_IS_ROOTS_PARENT,
	REG_IS_ROOTS_ROOT,
} from "./regexp";
export { ROOTS } from "./roots";
export {
	SKIP_PARAMS_KEY,
	SKIP_PARAMS_VALUE,
} from "./skippedParams";
export {
	OTHER_FILTER,
	OTHER_GENERATOR,
	OTHER_IN,
	OTHER_INIT,
	OTHER_QUESTION,
	OTHER_STARTER,
	STARTER_TYPES,
} from "./starters";
