import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
	cli: [{ type: "autogenerated", dirName: "." }],
	core: [{ type: "autogenerated", dirName: "." }],
	test: [{ type: "autogenerated", dirName: "." }],
};

export default sidebars;
